import { tHelper } from "../tHelper";
import { PartId } from "./PartId";

export const partIdT = tHelper<PartId>({
    ja: {
        skin: "肌",
        brain: "脳",
        ear: "耳",
        mouth: "口",
        tongue: "舌",
        throat: "喉",
        bust: "おっぱい",
        nipple: "乳首",
        hand: "手",
        arm: "腕",
        armpit: "腋",
        stomach: "おなか",
        back: "背中",
        clitoris: "陰核",
        urethra: "尿道",
        bladder: "膀胱",
        labia: "陰唇",
        vagina: "膣",
        portio: "子宮口",
        womb: "子宮",
        ovary: "卵巣",
        anus: "肛門",
        intestine: "腸",
        hip: "尻",
        thigh: "ふともも",
        leg: "脚",
        foot: "足",
    },
    zh: {
        skin: "皮肤",
        brain: "大脑",
        ear: "耳朵",
        mouth: "嘴",
        tongue: "舌头",
        throat: "喉咙",
        bust: "胸部",
        nipple: "乳头",
        hand: "手",
        arm: "手臂",
        armpit: "腋下",
        stomach: "腹部",
        back: "背部",
        clitoris: "阴蒂",
        urethra: "尿道",
        bladder: "膀胱",
        labia: "阴唇",
        vagina: "阴道",
        portio: "子宫口",
        womb: "子宫",
        ovary: "卵巢",
        anus: "肛门",
        intestine: "肠道",
        hip: "臀部",
        thigh: "大腿",
        leg: "腿",
        foot: "脚",
    },
});
